name: Coveralls

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          
      - name: Install Yarn 3 (Berry)
        run: npm install -g yarn@berry

      - name: Set up Yarn 3
        run: yarn set version berry

      - name: Install dependencies
        run: yarn install

      - name: Run tests with coverage
        run: yarn run test:coverage

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
