name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn 3 (Berry)
        run: npm install -g yarn@berry

      - name: Set up Yarn 3
        run: yarn set version berry

      - name: Install dependencies
        run: yarn install --immutable

      - name: Extract version from latest Git tag
        run: echo "Updating package.json version to latest tag"

      - name: Install jq
        run: sudo apt-get install jq

      - name: Use version and add to package.json
        run: |
          TAG_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))
          VERSION=${TAG_NAME#*v.}
          jq ".version = \"$VERSION\"" package.json > package.temp.json
          mv package.temp.json package.json
        env:
          VERSION: $VERSION

      - name: Build
        run: yarn build

      - name: Exclude source maps
        run: rm -rf dist/**/*.map

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "maphel"

      - name: Commit updated package.json
        run: |
          git add package.json
          git commit -m "Update package.json version to ${{ env.VERSION }}"
          git push origin HEAD:${{ github.ref }}
