name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  update-master-to-tagged-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Extract version from Git tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#*v}
          npm version $VERSION --no-git-tag-version
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Commit and push updated package.json on main
        run: |
          git config --local user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --local user.name "maphel"
          git add package.json
          git commit -m "Update package.json version to ${{ env.VERSION }} on main"
          git push origin main

  publish:
    needs: update-master-to-tagged-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: .yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Exclude source maps
        run: rm -rf dist/**/*.map

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
